
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



azure:
  storage:
    connection-string: ${STORAGE_CONNECTION_STRING}
    container-name: ${STORAGE_CONTAINER_NAME}